/*
 * CopyRight @xiaomi
 * This file is the generated by jidl tools for "PROJECT_ROOT/apps/frameworks/multimedia/media/feature/audio.jidl".
 */
/*
 * Copyright (C) 2025 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#include "audio.h"
#include "ajs_features_init.h"
#include "feature_description.h"
#include "feature_exports.h"
#include "feature_log.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

// build the predefined
// Struct predefine
extern const ObjectMapType system_audio_MetaInfo_struct_type;
// Struct predefine
extern const ObjectMapType system_audio_AudioState_struct_type;
// Struct predefine
extern const ObjectMapType system_audio_GetPalyStateParam_struct_type;

// build the array predefined
/****** for JIDL callback 'on_event' ******/
static const FeatureType system_audio_on_event_callback_param_types [] = {

    FT_PARAM_END
};

static const CallbackType system_audio_on_event_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_audio_on_event_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_audio_on_event_invoke(FeatureInstanceHandle handle, FtCallbackId cid)
{
    return FeatureInvokeCallback(handle, cid);
}

/****** for JIDL callback 'on_get_state' ******/
static const FeatureType system_audio_on_get_state_callback_param_types [] = {

    FT_MK_COMPLEX(&system_audio_AudioState_struct_type),
    FT_PARAM_END
};

static const CallbackType system_audio_on_get_state_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_audio_on_get_state_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_audio_on_get_state_invoke(FeatureInstanceHandle handle, FtCallbackId cid, system_audio_AudioState* state)
{
    return FeatureInvokeCallback(handle, cid, state);
}

/****** for JIDL callback 'on_void' ******/
static const FeatureType system_audio_on_void_callback_param_types [] = {

    FT_PARAM_END
};

static const CallbackType system_audio_on_void_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_audio_on_void_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_audio_on_void_invoke(FeatureInstanceHandle handle, FtCallbackId cid)
{
    return FeatureInvokeCallback(handle, cid);
}

/****** for JIDL callback 'on_fail' ******/
static const FeatureType system_audio_on_fail_callback_param_types [] = {

    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_audio_on_fail_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_audio_on_fail_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_audio_on_fail_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString data, FtInt code)
{
    return FeatureInvokeCallback(handle, cid, data, code);
}


/****** for JIDL struct 'MetaInfo' ******/
static ObjectMember system_audio_MetaInfo_struct_members [] = {
  {"title", FT_STRING, offsetof(system_audio_MetaInfo, title), sizeof(FtString)},
  {"album", FT_STRING, offsetof(system_audio_MetaInfo, album), sizeof(FtString)},
  {"artist", FT_STRING, offsetof(system_audio_MetaInfo, artist), sizeof(FtString)},
  {NULL}
};

// struct type defination
const ObjectMapType system_audio_MetaInfo_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_audio_MetaInfo) },
    .members = system_audio_MetaInfo_struct_members
};

system_audio_MetaInfo* system_audioMallocMetaInfo(void) {
  return (system_audio_MetaInfo*) FeatureMalloc(sizeof(system_audio_MetaInfo), FT_MK_COMPLEX(&system_audio_MetaInfo_struct_type)); 
}

FeatureType system_audio_MetaInfo_struct_get_type (void) {
    return (FeatureType)FT_MK_COMPLEX(&system_audio_MetaInfo_struct_type);
}

/****** for JIDL struct 'AudioState' ******/
static ObjectMember system_audio_AudioState_struct_members [] = {
  {"state", FT_STRING, offsetof(system_audio_AudioState, state), sizeof(FtString)},
  {"src", FT_STRING, offsetof(system_audio_AudioState, src), sizeof(FtString)},
  {"currentTime", FT_FLOAT, offsetof(system_audio_AudioState, currentTime), sizeof(FtFloat)},
  {"autoplay", FT_BOOLEAN, offsetof(system_audio_AudioState, autoplay), sizeof(FtBool)},
  {"loop", FT_BOOLEAN, offsetof(system_audio_AudioState, loop), sizeof(FtBool)},
  {"volume", FT_DOUBLE, offsetof(system_audio_AudioState, volume), sizeof(FtDouble)},
  {"muted", FT_BOOLEAN, offsetof(system_audio_AudioState, muted), sizeof(FtBool)},
  {"duration", FT_FLOAT, offsetof(system_audio_AudioState, duration), sizeof(FtFloat)},
  {"percent", FT_FLOAT, offsetof(system_audio_AudioState, percent), sizeof(FtFloat)},
  {NULL}
};

// struct type defination
const ObjectMapType system_audio_AudioState_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_audio_AudioState) },
    .members = system_audio_AudioState_struct_members
};

system_audio_AudioState* system_audioMallocAudioState(void) {
  return (system_audio_AudioState*) FeatureMalloc(sizeof(system_audio_AudioState), FT_MK_COMPLEX(&system_audio_AudioState_struct_type)); 
}

FeatureType system_audio_AudioState_struct_get_type (void) {
    return (FeatureType)FT_MK_COMPLEX(&system_audio_AudioState_struct_type);
}

/****** for JIDL struct 'GetPalyStateParam' ******/
static ObjectMember system_audio_GetPalyStateParam_struct_members [] = {
  {"success", FT_MK_COMPLEX(&system_audio_on_get_state_callback_type), offsetof(system_audio_GetPalyStateParam, success), sizeof(FtCallbackId)},
  {"fail", FT_MK_COMPLEX(&system_audio_on_fail_callback_type), offsetof(system_audio_GetPalyStateParam, fail), sizeof(FtCallbackId)},
  {"complete", FT_MK_COMPLEX(&system_audio_on_void_callback_type), offsetof(system_audio_GetPalyStateParam, complete), sizeof(FtCallbackId)},
  {NULL}
};

// struct type defination
const ObjectMapType system_audio_GetPalyStateParam_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_audio_GetPalyStateParam) },
    .members = system_audio_GetPalyStateParam_struct_members
};

system_audio_GetPalyStateParam* system_audioMallocGetPalyStateParam(void) {
  return (system_audio_GetPalyStateParam*) FeatureMalloc(sizeof(system_audio_GetPalyStateParam), FT_MK_COMPLEX(&system_audio_GetPalyStateParam_struct_type)); 
}

FeatureType system_audio_GetPalyStateParam_struct_get_type (void) {
    return (FeatureType)FT_MK_COMPLEX(&system_audio_GetPalyStateParam_struct_type);
}

// build for description members


/****** for JIDL property 'src' ******/
static void system_audio_get_src_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  *((FtString*)ret) = system_audio_get_src(handle, adata);
}

static void system_audio_set_src_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_src(handle, adata, *((FtString*)argv[0]));
}

static const MemberAccessor system_audio_src_member_accessor = {
  .getter_stub =system_audio_get_src_stub,
  .setter_stub =system_audio_set_src_stub,
  .type =FT_STRING
};

/****** for JIDL property 'meta' ******/

static void system_audio_set_meta_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_meta(handle, adata, *((system_audio_MetaInfo**)argv[0]));
}

static const MemberAccessor system_audio_meta_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_meta_stub,
  .type =FT_MK_COMPLEX(&system_audio_MetaInfo_struct_type),
};

/****** for JIDL property 'currentTime' ******/
static void system_audio_get_currentTime_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  *((FtFloat*)ret) = system_audio_get_currentTime(handle, adata);
}

static void system_audio_set_currentTime_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_currentTime(handle, adata, *((FtFloat*)argv[0]));
}

static const MemberAccessor system_audio_currentTime_member_accessor = {
  .getter_stub =system_audio_get_currentTime_stub,
  .setter_stub =system_audio_set_currentTime_stub,
  .type =FT_FLOAT
};

/****** for JIDL property 'duration' ******/
static void system_audio_get_duration_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  *((FtFloat*)ret) = system_audio_get_duration(handle, adata);
}



static const MemberAccessor system_audio_duration_member_accessor = {
  .getter_stub =system_audio_get_duration_stub,
  .setter_stub =NULL,
  .type =FT_FLOAT
};

/****** for JIDL property 'autoplay' ******/
static void system_audio_get_autoplay_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  *((FtBool*)ret) = system_audio_get_autoplay(handle, adata);
}

static void system_audio_set_autoplay_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_autoplay(handle, adata, *((FtBool*)argv[0]));
}

static const MemberAccessor system_audio_autoplay_member_accessor = {
  .getter_stub =system_audio_get_autoplay_stub,
  .setter_stub =system_audio_set_autoplay_stub,
  .type =FT_BOOLEAN
};

/****** for JIDL property 'loop' ******/
static void system_audio_get_loop_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  *((FtBool*)ret) = system_audio_get_loop(handle, adata);
}

static void system_audio_set_loop_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_loop(handle, adata, *((FtBool*)argv[0]));
}

static const MemberAccessor system_audio_loop_member_accessor = {
  .getter_stub =system_audio_get_loop_stub,
  .setter_stub =system_audio_set_loop_stub,
  .type =FT_BOOLEAN
};

/****** for JIDL property 'volume' ******/
static void system_audio_get_volume_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  *((FtDouble*)ret) = system_audio_get_volume(handle, adata);
}

static void system_audio_set_volume_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_volume(handle, adata, *((FtDouble*)argv[0]));
}

static const MemberAccessor system_audio_volume_member_accessor = {
  .getter_stub =system_audio_get_volume_stub,
  .setter_stub =system_audio_set_volume_stub,
  .type =FT_DOUBLE
};

/****** for JIDL property 'muted' ******/
static void system_audio_get_muted_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  *((FtBool*)ret) = system_audio_get_muted(handle, adata);
}

static void system_audio_set_muted_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_muted(handle, adata, *((FtBool*)argv[0]));
}

static const MemberAccessor system_audio_muted_member_accessor = {
  .getter_stub =system_audio_get_muted_stub,
  .setter_stub =system_audio_set_muted_stub,
  .type =FT_BOOLEAN
};

/****** for JIDL property 'streamType' ******/
static void system_audio_get_streamType_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  *((FtString*)ret) = system_audio_get_streamType(handle, adata);
}



static const MemberAccessor system_audio_streamType_member_accessor = {
  .getter_stub =system_audio_get_streamType_stub,
  .setter_stub =NULL,
  .type =FT_STRING
};

/****** for JIDL property 'percent' ******/
static void system_audio_get_percent_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  *((FtFloat*)ret) = system_audio_get_percent(handle, adata);
}



static const MemberAccessor system_audio_percent_member_accessor = {
  .getter_stub =system_audio_get_percent_stub,
  .setter_stub =NULL,
  .type =FT_FLOAT
};
/****** for JIDL function 'system_audio.play' ******/

static const FeatureType system_audio_play_param_types [] = {

    FT_PARAM_END
};

static void system_audio_play_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_audio_play_member_method = {
    .func_stub = system_audio_play_stub,
    .parameters = system_audio_play_param_types,
    .return_type = FT_VOID,
};

static void system_audio_play_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
system_audio_wrap_play(handle, adata);
}


/****** for JIDL function 'system_audio.pause' ******/

static const FeatureType system_audio_pause_param_types [] = {

    FT_PARAM_END
};

static void system_audio_pause_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_audio_pause_member_method = {
    .func_stub = system_audio_pause_stub,
    .parameters = system_audio_pause_param_types,
    .return_type = FT_VOID,
};

static void system_audio_pause_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
system_audio_wrap_pause(handle, adata);
}


/****** for JIDL function 'system_audio.stop' ******/

static const FeatureType system_audio_stop_param_types [] = {

    FT_PARAM_END
};

static void system_audio_stop_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_audio_stop_member_method = {
    .func_stub = system_audio_stop_stub,
    .parameters = system_audio_stop_param_types,
    .return_type = FT_VOID,
};

static void system_audio_stop_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
system_audio_wrap_stop(handle, adata);
}


/****** for JIDL function 'system_audio.getPlayState' ******/

static const FeatureType system_audio_getPlayState_param_types [] = {

    FT_MK_COMPLEX(&system_audio_GetPalyStateParam_struct_type),
    FT_PARAM_END
};

static void system_audio_getPlayState_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_audio_getPlayState_member_method = {
    .func_stub = system_audio_getPlayState_stub,
    .parameters = system_audio_getPlayState_param_types,
    .return_type = FT_VOID,
};

static void system_audio_getPlayState_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
system_audio_wrap_getPlayState(handle, adata, *((system_audio_GetPalyStateParam**)argv[0]));
}



/****** for JIDL property 'onplay' ******/

static void system_audio_set_onplay_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_onplay(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_onplay_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_onplay_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};

/****** for JIDL property 'onpause' ******/

static void system_audio_set_onpause_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_onpause(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_onpause_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_onpause_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};

/****** for JIDL property 'onstop' ******/

static void system_audio_set_onstop_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_onstop(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_onstop_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_onstop_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};

/****** for JIDL property 'onloadeddata' ******/

static void system_audio_set_onloadeddata_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_onloadeddata(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_onloadeddata_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_onloadeddata_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};

/****** for JIDL property 'onended' ******/

static void system_audio_set_onended_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_onended(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_onended_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_onended_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};

/****** for JIDL property 'ondurationchange' ******/

static void system_audio_set_ondurationchange_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_ondurationchange(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_ondurationchange_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_ondurationchange_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};

/****** for JIDL property 'ontimeupdate' ******/

static void system_audio_set_ontimeupdate_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_ontimeupdate(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_ontimeupdate_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_ontimeupdate_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};

/****** for JIDL property 'onerror' ******/

static void system_audio_set_onerror_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_onerror(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_onerror_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_onerror_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};

/****** for JIDL property 'onctrlplayprev' ******/

static void system_audio_set_onctrlplayprev_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_onctrlplayprev(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_onctrlplayprev_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_onctrlplayprev_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};

/****** for JIDL property 'onctrlplaynext' ******/

static void system_audio_set_onctrlplaynext_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {

  system_audio_set_onctrlplaynext(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_audio_onctrlplaynext_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_audio_set_onctrlplaynext_stub,
  .type =FT_MK_COMPLEX(&system_audio_on_event_callback_type),
};
// define the interface member array

// description members
static const Member system_audio_members[] = {
  { 
    .type = MEMBER_ACCESSOR,
    .name = "src",
    .accessor = &system_audio_src_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "meta",
    .accessor = &system_audio_meta_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "currentTime",
    .accessor = &system_audio_currentTime_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "duration",
    .accessor = &system_audio_duration_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "autoplay",
    .accessor = &system_audio_autoplay_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "loop",
    .accessor = &system_audio_loop_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "volume",
    .accessor = &system_audio_volume_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "muted",
    .accessor = &system_audio_muted_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "streamType",
    .accessor = &system_audio_streamType_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "percent",
    .accessor = &system_audio_percent_member_accessor,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "play",
    .method = &system_audio_play_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "pause",
    .method = &system_audio_pause_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "stop",
    .method = &system_audio_stop_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "getPlayState",
    .method = &system_audio_getPlayState_member_method,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "onplay",
    .accessor = &system_audio_onplay_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "onpause",
    .accessor = &system_audio_onpause_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "onstop",
    .accessor = &system_audio_onstop_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "onloadeddata",
    .accessor = &system_audio_onloadeddata_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "onended",
    .accessor = &system_audio_onended_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "ondurationchange",
    .accessor = &system_audio_ondurationchange_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "ontimeupdate",
    .accessor = &system_audio_ontimeupdate_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "onerror",
    .accessor = &system_audio_onerror_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "onctrlplayprev",
    .accessor = &system_audio_onctrlplayprev_member_accessor,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "onctrlplaynext",
    .accessor = &system_audio_onctrlplaynext_member_accessor,
    },
};

// callbacks
static const struct FeatureCallbacks system_audio_callbacks = {
    system_audio_onRegister,
    system_audio_onCreate,
    system_audio_onRequired,
    system_audio_onDetached,
    system_audio_onDestroy,
    system_audio_onUnregister
};
static const FeatureDescription system_audio_desc = {
  .version = 1,
  .name = "system.audio",
  .description = "system.audio",
  .dynamic = false,
  .native_callbacks = &system_audio_callbacks,
  .member_count = countof(system_audio_members),
  .members = system_audio_members
};
QAPPFEATURE_INIT(system_audio)
{
    return FeatureRegisterFeature(handle, &system_audio_desc);
}


/* clang-format on */