/*
 * CopyRight @xiaomi
 * This file is the generated by jidl tools for "PROJECT_ROOT/apps/frameworks/multimedia/media/feature/audio.jidl".
 */
/*
 * Copyright (C) 2025 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* clang-format off */
#ifndef JIDL_RUST_GEN_MODULE_SYSTEM_AUDIO_H
#define JIDL_RUST_GEN_MODULE_SYSTEM_AUDIO_H

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_audio_onRegister(const char* feature_name);

void system_audio_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);

void system_audio_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);

void system_audio_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);

void system_audio_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);

void system_audio_onUnregister(const char* feature_name);

// build the predefined
typedef struct system_audio_MetaInfo system_audio_MetaInfo;
typedef struct system_audio_AudioState system_audio_AudioState;
typedef struct system_audio_GetPalyStateParam system_audio_GetPalyStateParam;
// Struct define

typedef struct system_audio_MetaInfo {
    FtString title;
    FtString album;
    FtString artist;
} system_audio_MetaInfo;

system_audio_MetaInfo* system_audioMallocMetaInfo(void);

FeatureType system_audio_MetaInfo_struct_get_type (void);
// callback

// for JIDL callback 'on_event'
FtBool system_audio_on_event_invoke(FeatureInstanceHandle handle, FtCallbackId cid);
  
// callback

// for JIDL callback 'on_get_state'
FtBool system_audio_on_get_state_invoke(FeatureInstanceHandle handle, FtCallbackId cid, system_audio_AudioState* state);
  
// Struct define

typedef struct system_audio_AudioState {
    FtString state;
    FtString src;
    FtFloat currentTime;
    FtBool autoplay;
    FtBool loop;
    FtDouble volume;
    FtBool muted;
    FtFloat duration;
    FtFloat percent;
} system_audio_AudioState;

system_audio_AudioState* system_audioMallocAudioState(void);

FeatureType system_audio_AudioState_struct_get_type (void);
// Struct define

typedef struct system_audio_GetPalyStateParam {
    FtCallbackId success;
    FtCallbackId fail;
    FtCallbackId complete;
} system_audio_GetPalyStateParam;

system_audio_GetPalyStateParam* system_audioMallocGetPalyStateParam(void);

FeatureType system_audio_GetPalyStateParam_struct_get_type (void);
// callback

// for JIDL callback 'on_void'
FtBool system_audio_on_void_invoke(FeatureInstanceHandle handle, FtCallbackId cid);
  
// callback

// for JIDL callback 'on_fail'
FtBool system_audio_on_fail_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString data, FtInt code);
  
  
FtString system_audio_get_src(FeatureInstanceHandle handle, AppendData adata);
void system_audio_set_src(FeatureInstanceHandle handle, AppendData adata, FtString src);
  
void system_audio_set_meta(FeatureInstanceHandle handle, AppendData adata, system_audio_MetaInfo* meta);
  
FtFloat system_audio_get_currentTime(FeatureInstanceHandle handle, AppendData adata);
void system_audio_set_currentTime(FeatureInstanceHandle handle, AppendData adata, FtFloat currentTime);
  
FtFloat system_audio_get_duration(FeatureInstanceHandle handle, AppendData adata);
  
FtBool system_audio_get_autoplay(FeatureInstanceHandle handle, AppendData adata);
void system_audio_set_autoplay(FeatureInstanceHandle handle, AppendData adata, FtBool autoplay);
  
FtBool system_audio_get_loop(FeatureInstanceHandle handle, AppendData adata);
void system_audio_set_loop(FeatureInstanceHandle handle, AppendData adata, FtBool loop);
  
FtDouble system_audio_get_volume(FeatureInstanceHandle handle, AppendData adata);
void system_audio_set_volume(FeatureInstanceHandle handle, AppendData adata, FtDouble volume);
  
FtBool system_audio_get_muted(FeatureInstanceHandle handle, AppendData adata);
void system_audio_set_muted(FeatureInstanceHandle handle, AppendData adata, FtBool muted);
  
FtString system_audio_get_streamType(FeatureInstanceHandle handle, AppendData adata);
  
FtFloat system_audio_get_percent(FeatureInstanceHandle handle, AppendData adata);
  
void system_audio_wrap_play(FeatureInstanceHandle handle, AppendData adata);
  
void system_audio_wrap_pause(FeatureInstanceHandle handle, AppendData adata);
  
void system_audio_wrap_stop(FeatureInstanceHandle handle, AppendData adata);
  
void system_audio_wrap_getPlayState(FeatureInstanceHandle handle, AppendData adata, system_audio_GetPalyStateParam* p);
  
void system_audio_set_onplay(FeatureInstanceHandle handle, AppendData adata, FtCallbackId onplay);
  
void system_audio_set_onpause(FeatureInstanceHandle handle, AppendData adata, FtCallbackId onpause);
  
void system_audio_set_onstop(FeatureInstanceHandle handle, AppendData adata, FtCallbackId onstop);
  
void system_audio_set_onloadeddata(FeatureInstanceHandle handle, AppendData adata, FtCallbackId onloadeddata);
  
void system_audio_set_onended(FeatureInstanceHandle handle, AppendData adata, FtCallbackId onended);
  
void system_audio_set_ondurationchange(FeatureInstanceHandle handle, AppendData adata, FtCallbackId ondurationchange);
  
void system_audio_set_ontimeupdate(FeatureInstanceHandle handle, AppendData adata, FtCallbackId ontimeupdate);
  
void system_audio_set_onerror(FeatureInstanceHandle handle, AppendData adata, FtCallbackId onerror);
  
void system_audio_set_onctrlplayprev(FeatureInstanceHandle handle, AppendData adata, FtCallbackId onctrlplayprev);
  
void system_audio_set_onctrlplaynext(FeatureInstanceHandle handle, AppendData adata, FtCallbackId onctrlplaynext);// define the event id
enum {
  system_audio_event_id_begin = 1,








  system_audio_event_id_end,
};

/* clang-format on */
#endif //  JIDL_RUST_GEN_MODULE_SYSTEM_AUDIO_H
