/*
 * CopyRight @xiaomi
 * This file is the generated by jidl tools for "PROJECT_ROOT/apps/frameworks/multimedia/media/feature/record.jidl".
 */
/*
 * Copyright (C) 2025 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#include "record.h"
#include "ajs_features_init.h"
#include "feature_description.h"
#include "feature_exports.h"
#include "feature_log.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

// build the predefined
// Struct predefine
extern const ObjectMapType system_record_SetInfo_struct_type;

// build the array predefined
/****** for JIDL callback 'complete_cb' ******/
static const FeatureType system_record_complete_cb_callback_param_types [] = {

    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_record_complete_cb_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_record_complete_cb_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_record_complete_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString msg)
{
    return FeatureInvokeCallback(handle, cid, msg);
}

/****** for JIDL callback 'success_cb' ******/
static const FeatureType system_record_success_cb_callback_param_types [] = {

    FT_ANY_REF,
    FT_PARAM_END
};

static const CallbackType system_record_success_cb_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_record_success_cb_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_record_success_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtAny data)
{
    return FeatureInvokeCallback(handle, cid, data);
}

/****** for JIDL callback 'fail_cb' ******/
static const FeatureType system_record_fail_cb_callback_param_types [] = {

    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_record_fail_cb_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_record_fail_cb_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_record_fail_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString msg, FtInt code)
{
    return FeatureInvokeCallback(handle, cid, msg, code);
}

/****** for optional type of 'FT_INT' ******/
static OptionalType system_record_SetInfo_numberOfChannels_FT_INT_opt_type = {
  .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
  .type = FT_INT,
  .lval = 1
};

/****** for optional type of 'FT_STRING' ******/
static OptionalType system_record_SetInfo_format_FT_STRING_opt_type = {
  .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
  .type = FT_STRING,
  .str = "pcm"
};

/****** for optional type of 'FT_INT' ******/
static OptionalType system_record_SetInfo_duration_FT_INT_opt_type = {
  .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
  .type = FT_INT,
  .lval = 0
};

/****** for optional type of 'FT_INT' ******/
static OptionalType system_record_SetInfo_sampleRate_FT_INT_opt_type = {
  .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
  .type = FT_INT,
  .lval = 8000
};

/****** for optional type of 'FT_INT' ******/
static OptionalType system_record_SetInfo_encodeBitRate_FT_INT_opt_type = {
  .header = { .type = COMPLEX_OPTIONAL, .size = sizeof(OptionalType) },
  .type = FT_INT,
  .lval = 16000
};


/****** for JIDL struct 'SetInfo' ******/
static ObjectMember system_record_SetInfo_struct_members [] = {
  {"duration", FT_MK_OPTIONAL(&system_record_SetInfo_duration_FT_INT_opt_type), offsetof(system_record_SetInfo, duration), sizeof(FtInt)},
  {"sampleRate", FT_MK_OPTIONAL(&system_record_SetInfo_sampleRate_FT_INT_opt_type), offsetof(system_record_SetInfo, sampleRate), sizeof(FtInt)},
  {"numberOfChannels", FT_MK_OPTIONAL(&system_record_SetInfo_numberOfChannels_FT_INT_opt_type), offsetof(system_record_SetInfo, numberOfChannels), sizeof(FtInt)},
  {"encodeBitRate", FT_MK_OPTIONAL(&system_record_SetInfo_encodeBitRate_FT_INT_opt_type), offsetof(system_record_SetInfo, encodeBitRate), sizeof(FtInt)},
  {"format", FT_MK_OPTIONAL(&system_record_SetInfo_format_FT_STRING_opt_type), offsetof(system_record_SetInfo, format), sizeof(FtString)},
  {"success", FT_MK_COMPLEX(&system_record_success_cb_callback_type), offsetof(system_record_SetInfo, success), sizeof(FtCallbackId)},
  {"fail", FT_MK_COMPLEX(&system_record_fail_cb_callback_type), offsetof(system_record_SetInfo, fail), sizeof(FtCallbackId)},
  {"complete", FT_MK_COMPLEX(&system_record_complete_cb_callback_type), offsetof(system_record_SetInfo, complete), sizeof(FtCallbackId)},
  {NULL}
};

// struct type defination
const ObjectMapType system_record_SetInfo_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_record_SetInfo) },
    .members = system_record_SetInfo_struct_members
};

system_record_SetInfo* system_recordMallocSetInfo(void) {
  return (system_record_SetInfo*) FeatureMalloc(sizeof(system_record_SetInfo), FT_MK_COMPLEX(&system_record_SetInfo_struct_type)); 
}

FeatureType system_record_SetInfo_struct_get_type (void) {
    return (FeatureType)FT_MK_COMPLEX(&system_record_SetInfo_struct_type);
}

// build for description members

/****** for JIDL function 'system_record.start' ******/

static const FeatureType system_record_start_param_types [] = {

    FT_MK_COMPLEX(&system_record_SetInfo_struct_type),
    FT_PARAM_END
};

static void system_record_start_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_record_start_member_method = {
    .func_stub = system_record_start_stub,
    .parameters = system_record_start_param_types,
    .return_type = FT_VOID,
};

static void system_record_start_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
system_record_wrap_start(handle, adata, *((system_record_SetInfo**)argv[0]));
}


/****** for JIDL function 'system_record.stop' ******/

static const FeatureType system_record_stop_param_types [] = {

    FT_PARAM_END
};

static void system_record_stop_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_record_stop_member_method = {
    .func_stub = system_record_stop_stub,
    .parameters = system_record_stop_param_types,
    .return_type = FT_VOID,
};

static void system_record_stop_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
system_record_wrap_stop(handle, adata);
}


// define the interface member array

// description members
static const Member system_record_members[] = {
  { 
    .type = MEMBER_METHOD,
    .name = "start",
    .method = &system_record_start_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "stop",
    .method = &system_record_stop_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_record_callbacks = {
    system_record_onRegister,
    system_record_onCreate,
    system_record_onRequired,
    system_record_onDetached,
    system_record_onDestroy,
    system_record_onUnregister
};
static const FeatureDescription system_record_desc = {
  .version = 1,
  .name = "system.record",
  .description = "system.record",
  .dynamic = false,
  .native_callbacks = &system_record_callbacks,
  .member_count = countof(system_record_members),
  .members = system_record_members
};
QAPPFEATURE_INIT(system_record)
{
    return FeatureRegisterFeature(handle, &system_record_desc);
}


/* clang-format on */