/*
 * CopyRight @xiaomi
 * This file is the generated by jidl tools for "PROJECT_ROOT/apps/frameworks/multimedia/media/feature/record.jidl".
 */
/*
 * Copyright (C) 2025 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* clang-format off */
#ifndef JIDL_RUST_GEN_MODULE_SYSTEM_RECORD_H
#define JIDL_RUST_GEN_MODULE_SYSTEM_RECORD_H

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_record_onRegister(const char* feature_name);

void system_record_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);

void system_record_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);

void system_record_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);

void system_record_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);

void system_record_onUnregister(const char* feature_name);

// build the predefined
typedef struct system_record_SetInfo system_record_SetInfo;
// callback

// for JIDL callback 'complete_cb'
FtBool system_record_complete_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString msg);
  
// callback

// for JIDL callback 'success_cb'
FtBool system_record_success_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtAny data);
  
// Struct define

typedef struct system_record_SetInfo {
    FtInt duration;
    FtInt sampleRate;
    FtInt numberOfChannels;
    FtInt encodeBitRate;
    FtString format;
    FtCallbackId success;
    FtCallbackId fail;
    FtCallbackId complete;
} system_record_SetInfo;

system_record_SetInfo* system_recordMallocSetInfo(void);

FeatureType system_record_SetInfo_struct_get_type (void);
// callback

// for JIDL callback 'fail_cb'
FtBool system_record_fail_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString msg, FtInt code);
  
  
void system_record_wrap_start(FeatureInstanceHandle handle, AppendData adata, system_record_SetInfo* info);
  
void system_record_wrap_stop(FeatureInstanceHandle handle, AppendData adata);// define the event id
enum {
  system_record_event_id_begin = 1,










  system_record_event_id_end,
};

/* clang-format on */
#endif //  JIDL_RUST_GEN_MODULE_SYSTEM_RECORD_H
