/*
 * CopyRight @xiaomi
 * This file is the generated by jidl tools for "PROJECT_ROOT/apps/frameworks/multimedia/media/feature/session.jidl".
 */
/*
 * Copyright (C) 2025 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* clang-format off */
#ifndef JIDL_RUST_GEN_MODULE_SYSTEM_MEDIA_SESSION_H
#define JIDL_RUST_GEN_MODULE_SYSTEM_MEDIA_SESSION_H

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_media_session_onRegister(const char* feature_name);

void system_media_session_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);

void system_media_session_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);

void system_media_session_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);

void system_media_session_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);

void system_media_session_onUnregister(const char* feature_name);

// build the predefined
typedef struct system_media_session_Feedback system_media_session_Feedback;
// callback

// for JIDL callback 'complete_cb'
FtBool system_media_session_complete_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid);
  
// Interface define

// VTable defines for interface 'Session'
typedef struct _system_media_session_Session_interface_vtable {
    VTable base; // vtable base
    void (*start)(FeatureInterfaceHandle handle, AppendData adata , system_media_session_Feedback* fb);
    void (*pause)(FeatureInterfaceHandle handle, AppendData adata , system_media_session_Feedback* fb);
    void (*stop)(FeatureInterfaceHandle handle, AppendData adata , system_media_session_Feedback* fb);
    void (*prev)(FeatureInterfaceHandle handle, AppendData adata , system_media_session_Feedback* fb);
    void (*next)(FeatureInterfaceHandle handle, AppendData adata , system_media_session_Feedback* fb);
    void (*increaseVolume)(FeatureInterfaceHandle handle, AppendData adata , system_media_session_Feedback* fb);
    void (*decreaseVolume)(FeatureInterfaceHandle handle, AppendData adata , system_media_session_Feedback* fb);
    void (*set_onEvent)(FeatureInstanceHandle handle, AppendData adata, FtCallbackId onEvent);
} system_media_session_Session_interface_vtable;

FeatureInterfaceHandle system_media_session_Session_create(FeatureInstanceHandle handle, system_media_session_Session_interface_vtable* vtable, void* data);

// callback

// for JIDL callback 'fail_cb'
FtBool system_media_session_fail_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString errorMsg, FtInt code);
  
// callback

// for JIDL callback 'status_cb'
FtBool system_media_session_status_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString status);
  
// callback

// for JIDL callback 'success_cb'
FtBool system_media_session_success_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString msg);
  
// Struct define

typedef struct system_media_session_Feedback {
    FtCallbackId success;
    FtCallbackId fail;
    FtCallbackId complete;
} system_media_session_Feedback;

system_media_session_Feedback* system_media_sessionMallocFeedback(void);

FeatureType system_media_session_Feedback_struct_get_type (void);
  
FeatureInterfaceHandle system_media_session_wrap_createSession(FeatureInstanceHandle handle, AppendData adata, FtString params);

// vtable functions for interface target 'media_session'
void system_media_session_Session_interface_media_session_finalize(FeatureInterfaceHandle handle);
void system_media_session_Session_interface_media_session_start(
        FeatureInterfaceHandle handle, AppendData adata, system_media_session_Feedback* fb);
void system_media_session_Session_interface_media_session_pause(
        FeatureInterfaceHandle handle, AppendData adata, system_media_session_Feedback* fb);
void system_media_session_Session_interface_media_session_stop(
        FeatureInterfaceHandle handle, AppendData adata, system_media_session_Feedback* fb);
void system_media_session_Session_interface_media_session_prev(
        FeatureInterfaceHandle handle, AppendData adata, system_media_session_Feedback* fb);
void system_media_session_Session_interface_media_session_next(
        FeatureInterfaceHandle handle, AppendData adata, system_media_session_Feedback* fb);
void system_media_session_Session_interface_media_session_increaseVolume(
        FeatureInterfaceHandle handle, AppendData adata, system_media_session_Feedback* fb);
void system_media_session_Session_interface_media_session_decreaseVolume(
        FeatureInterfaceHandle handle, AppendData adata, system_media_session_Feedback* fb);
void system_media_session_Session_interface_media_session_set_onEvent(
        FeatureInstanceHandle handle, AppendData adata, FtCallbackId);

FeatureInterfaceHandle system_media_session_createSession_instance(FeatureInstanceHandle feature);// define the event id
enum {
  system_media_session_event_id_begin = 1,







  system_media_session_event_id_end,
};

/* clang-format on */
#endif //  JIDL_RUST_GEN_MODULE_SYSTEM_MEDIA_SESSION_H
