/*
 * CopyRight @xiaomi
 * This file is the generated by jidl tools for "PROJECT_ROOT/apps/frameworks/multimedia/media/feature/session.jidl".
 */
/*
 * Copyright (C) 2025 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* clang-format off */

#include "session.h"
#include "ajs_features_init.h"
#include "feature_description.h"
#include "feature_exports.h"
#include "feature_log.h"

#define countof(x) (sizeof(x) / sizeof(x[0]))

// build the predefined
// Interface predefine
extern const InterfaceType system_media_session_Session_interface_type;
// Struct predefine
extern const ObjectMapType system_media_session_Feedback_struct_type;

// build the array predefined
/****** for JIDL callback 'complete_cb' ******/
static const FeatureType system_media_session_complete_cb_callback_param_types [] = {

    FT_PARAM_END
};

static const CallbackType system_media_session_complete_cb_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_media_session_complete_cb_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_media_session_complete_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid)
{
    return FeatureInvokeCallback(handle, cid);
}

/****** for JIDL callback 'fail_cb' ******/
static const FeatureType system_media_session_fail_cb_callback_param_types [] = {

    FT_STRING,
    FT_INT,
    FT_PARAM_END
};

static const CallbackType system_media_session_fail_cb_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_media_session_fail_cb_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_media_session_fail_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString errorMsg, FtInt code)
{
    return FeatureInvokeCallback(handle, cid, errorMsg, code);
}

/****** for JIDL callback 'status_cb' ******/
static const FeatureType system_media_session_status_cb_callback_param_types [] = {

    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_media_session_status_cb_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_media_session_status_cb_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_media_session_status_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString status)
{
    return FeatureInvokeCallback(handle, cid, status);
}

/****** for JIDL callback 'success_cb' ******/
static const FeatureType system_media_session_success_cb_callback_param_types [] = {

    FT_STRING,
    FT_PARAM_END
};

static const CallbackType system_media_session_success_cb_callback_type = {
    .header = { .type = COMPLEX_CALLBACK, .size = sizeof(FtCallbackId) },
    .parameters = system_media_session_success_cb_callback_param_types,
    .return_type = FT_VOID
};

FtBool system_media_session_success_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString msg)
{
    return FeatureInvokeCallback(handle, cid, msg);
}

// Interface define
// define the interface members

/****** for JIDL function 'system_media_session_Session.start' ******/

static const FeatureType system_media_session_Session_start_param_types [] = {

    FT_MK_COMPLEX(&system_media_session_Feedback_struct_type),
    FT_PARAM_END
};

static void system_media_session_Session_start_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_media_session_Session_start_member_method = {
    .func_stub = system_media_session_Session_start_stub,
    .parameters = system_media_session_Session_start_param_types,
    .return_type = FT_VOID,
};
typedef void (*system_media_session_Session_start_func_t)(FeatureInterfaceHandle,
    AppendData, system_media_session_Feedback* fb);


static void system_media_session_Session_start_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
    system_media_session_Session_start_func_t pfunc =
        (system_media_session_Session_start_func_t)FeatureGetInterfaceMember(handle, 0);
pfunc(handle, adata, *((system_media_session_Feedback**)argv[0]));
}


/****** for JIDL function 'system_media_session_Session.pause' ******/

static const FeatureType system_media_session_Session_pause_param_types [] = {

    FT_MK_COMPLEX(&system_media_session_Feedback_struct_type),
    FT_PARAM_END
};

static void system_media_session_Session_pause_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_media_session_Session_pause_member_method = {
    .func_stub = system_media_session_Session_pause_stub,
    .parameters = system_media_session_Session_pause_param_types,
    .return_type = FT_VOID,
};
typedef void (*system_media_session_Session_pause_func_t)(FeatureInterfaceHandle,
    AppendData, system_media_session_Feedback* fb);


static void system_media_session_Session_pause_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
    system_media_session_Session_pause_func_t pfunc =
        (system_media_session_Session_pause_func_t)FeatureGetInterfaceMember(handle, 1);
pfunc(handle, adata, *((system_media_session_Feedback**)argv[0]));
}


/****** for JIDL function 'system_media_session_Session.stop' ******/

static const FeatureType system_media_session_Session_stop_param_types [] = {

    FT_MK_COMPLEX(&system_media_session_Feedback_struct_type),
    FT_PARAM_END
};

static void system_media_session_Session_stop_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_media_session_Session_stop_member_method = {
    .func_stub = system_media_session_Session_stop_stub,
    .parameters = system_media_session_Session_stop_param_types,
    .return_type = FT_VOID,
};
typedef void (*system_media_session_Session_stop_func_t)(FeatureInterfaceHandle,
    AppendData, system_media_session_Feedback* fb);


static void system_media_session_Session_stop_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
    system_media_session_Session_stop_func_t pfunc =
        (system_media_session_Session_stop_func_t)FeatureGetInterfaceMember(handle, 2);
pfunc(handle, adata, *((system_media_session_Feedback**)argv[0]));
}


/****** for JIDL function 'system_media_session_Session.prev' ******/

static const FeatureType system_media_session_Session_prev_param_types [] = {

    FT_MK_COMPLEX(&system_media_session_Feedback_struct_type),
    FT_PARAM_END
};

static void system_media_session_Session_prev_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_media_session_Session_prev_member_method = {
    .func_stub = system_media_session_Session_prev_stub,
    .parameters = system_media_session_Session_prev_param_types,
    .return_type = FT_VOID,
};
typedef void (*system_media_session_Session_prev_func_t)(FeatureInterfaceHandle,
    AppendData, system_media_session_Feedback* fb);


static void system_media_session_Session_prev_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
    system_media_session_Session_prev_func_t pfunc =
        (system_media_session_Session_prev_func_t)FeatureGetInterfaceMember(handle, 3);
pfunc(handle, adata, *((system_media_session_Feedback**)argv[0]));
}


/****** for JIDL function 'system_media_session_Session.next' ******/

static const FeatureType system_media_session_Session_next_param_types [] = {

    FT_MK_COMPLEX(&system_media_session_Feedback_struct_type),
    FT_PARAM_END
};

static void system_media_session_Session_next_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_media_session_Session_next_member_method = {
    .func_stub = system_media_session_Session_next_stub,
    .parameters = system_media_session_Session_next_param_types,
    .return_type = FT_VOID,
};
typedef void (*system_media_session_Session_next_func_t)(FeatureInterfaceHandle,
    AppendData, system_media_session_Feedback* fb);


static void system_media_session_Session_next_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
    system_media_session_Session_next_func_t pfunc =
        (system_media_session_Session_next_func_t)FeatureGetInterfaceMember(handle, 4);
pfunc(handle, adata, *((system_media_session_Feedback**)argv[0]));
}


/****** for JIDL function 'system_media_session_Session.increaseVolume' ******/

static const FeatureType system_media_session_Session_increaseVolume_param_types [] = {

    FT_MK_COMPLEX(&system_media_session_Feedback_struct_type),
    FT_PARAM_END
};

static void system_media_session_Session_increaseVolume_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_media_session_Session_increaseVolume_member_method = {
    .func_stub = system_media_session_Session_increaseVolume_stub,
    .parameters = system_media_session_Session_increaseVolume_param_types,
    .return_type = FT_VOID,
};
typedef void (*system_media_session_Session_increaseVolume_func_t)(FeatureInterfaceHandle,
    AppendData, system_media_session_Feedback* fb);


static void system_media_session_Session_increaseVolume_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
    system_media_session_Session_increaseVolume_func_t pfunc =
        (system_media_session_Session_increaseVolume_func_t)FeatureGetInterfaceMember(handle, 5);
pfunc(handle, adata, *((system_media_session_Feedback**)argv[0]));
}


/****** for JIDL function 'system_media_session_Session.decreaseVolume' ******/

static const FeatureType system_media_session_Session_decreaseVolume_param_types [] = {

    FT_MK_COMPLEX(&system_media_session_Feedback_struct_type),
    FT_PARAM_END
};

static void system_media_session_Session_decreaseVolume_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_media_session_Session_decreaseVolume_member_method = {
    .func_stub = system_media_session_Session_decreaseVolume_stub,
    .parameters = system_media_session_Session_decreaseVolume_param_types,
    .return_type = FT_VOID,
};
typedef void (*system_media_session_Session_decreaseVolume_func_t)(FeatureInterfaceHandle,
    AppendData, system_media_session_Feedback* fb);


static void system_media_session_Session_decreaseVolume_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
    system_media_session_Session_decreaseVolume_func_t pfunc =
        (system_media_session_Session_decreaseVolume_func_t)FeatureGetInterfaceMember(handle, 6);
pfunc(handle, adata, *((system_media_session_Feedback**)argv[0]));
}



/****** for JIDL property 'onEvent' ******/

static void system_media_session_Session_set_onEvent_stub(
    FeatureInterfaceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
  typedef void (*pset_t)(FeatureInterfaceHandle handle, AppendData adata, FtCallbackId);
  pset_t pset = (pset_t)FeatureGetInterfaceMember(handle, 7);

  pset(handle, adata, *((FtCallbackId*)argv[0]));
}

static const MemberAccessor system_media_session_Session_onEvent_member_accessor = {
  .getter_stub =NULL,
  .setter_stub =system_media_session_Session_set_onEvent_stub,
  .type =FT_MK_COMPLEX(&system_media_session_status_cb_callback_type),
};
// define the interface member array

// description members
static const Member system_media_session_Session_members[] = {
  { 
    .type = MEMBER_METHOD,
    .name = "start",
    .method = &system_media_session_Session_start_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "pause",
    .method = &system_media_session_Session_pause_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "stop",
    .method = &system_media_session_Session_stop_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "prev",
    .method = &system_media_session_Session_prev_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "next",
    .method = &system_media_session_Session_next_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "increaseVolume",
    .method = &system_media_session_Session_increaseVolume_member_method,
    },
  { 
    .type = MEMBER_METHOD,
    .name = "decreaseVolume",
    .method = &system_media_session_Session_decreaseVolume_member_method,
    },
  { 
    .type = MEMBER_ACCESSOR,
    .name = "onEvent",
    .accessor = &system_media_session_Session_onEvent_member_accessor,
    },
};

static const FeatureDescription system_media_session_Session_desc = {
  .version = 1,
  .name = "Session",
  .description = "Session",
  .dynamic = true,
  .native_callbacks = NULL,
   
  .member_count = countof(system_media_session_Session_members),
  .members = system_media_session_Session_members
};

const InterfaceType system_media_session_Session_interface_type = {
    .header = { .type = COMPLEX_INTERFACE, .size = 0 },
    .desc = &system_media_session_Session_desc
};

FeatureInterfaceHandle system_media_session_Session_create(
        FeatureInstanceHandle handle, system_media_session_Session_interface_vtable* vtable, void* data) {
  if (vtable == NULL) {
    return NULL;
  }
  vtable->base.size = (sizeof(*vtable) - (sizeof(VTable))) / sizeof(void*);
  vtable->base.members = (const NativeFunc*)(&vtable->base + 1);
  FeatureInterfaceHandle hInterface = FeatureCreateInterface(handle, &(vtable->base));
  if (data) {
    FeatureSetObjectData(hInterface, data);
  }
  return hInterface;
}

/****** for JIDL struct 'Feedback' ******/
static ObjectMember system_media_session_Feedback_struct_members [] = {
  {"success", FT_MK_COMPLEX(&system_media_session_success_cb_callback_type), offsetof(system_media_session_Feedback, success), sizeof(FtCallbackId)},
  {"fail", FT_MK_COMPLEX(&system_media_session_fail_cb_callback_type), offsetof(system_media_session_Feedback, fail), sizeof(FtCallbackId)},
  {"complete", FT_MK_COMPLEX(&system_media_session_complete_cb_callback_type), offsetof(system_media_session_Feedback, complete), sizeof(FtCallbackId)},
  {NULL}
};

// struct type defination
const ObjectMapType system_media_session_Feedback_struct_type = {
    .header = { .type = COMPLEX_STRUCT_MAP, .size = sizeof(system_media_session_Feedback) },
    .members = system_media_session_Feedback_struct_members
};

system_media_session_Feedback* system_media_sessionMallocFeedback(void) {
  return (system_media_session_Feedback*) FeatureMalloc(sizeof(system_media_session_Feedback), FT_MK_COMPLEX(&system_media_session_Feedback_struct_type)); 
}

FeatureType system_media_session_Feedback_struct_get_type (void) {
    return (FeatureType)FT_MK_COMPLEX(&system_media_session_Feedback_struct_type);
}

// build for description members

/****** for JIDL function 'system_media_session.createSession' ******/
// constructor function for 'createSession'
FeatureInterfaceHandle system_media_session_createSession_instance(FeatureInstanceHandle feature) {
    static system_media_session_Session_interface_vtable media_session_vtable = {
      .base = { .finalizer = (NativeFunc)system_media_session_Session_interface_media_session_finalize },
      .start = system_media_session_Session_interface_media_session_start,
      .pause = system_media_session_Session_interface_media_session_pause,
      .stop = system_media_session_Session_interface_media_session_stop,
      .prev = system_media_session_Session_interface_media_session_prev,
      .next = system_media_session_Session_interface_media_session_next,
      .increaseVolume = system_media_session_Session_interface_media_session_increaseVolume,
      .decreaseVolume = system_media_session_Session_interface_media_session_decreaseVolume,
      .set_onEvent = system_media_session_Session_interface_media_session_set_onEvent,
    };

    return system_media_session_Session_create(feature, &media_session_vtable, NULL);
}

static const FeatureType system_media_session_createSession_param_types [] = {

    FT_STRING,
    FT_PARAM_END
};

static void system_media_session_createSession_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret);

static const MemberMethod system_media_session_createSession_member_method = {
    .func_stub = system_media_session_createSession_stub,
    .parameters = system_media_session_createSession_param_types,
    .return_type = FT_MK_COMPLEX(&system_media_session_Session_interface_type),
};

static void system_media_session_createSession_stub (
        FeatureInstanceHandle handle, AppendData adata, void** argv, int argc, void* ret) {
*((FeatureInterfaceHandle*)ret) = system_media_session_wrap_createSession(handle, adata, *((FtString*)argv[0]));
}


// define the interface member array

// description members
static const Member system_media_session_members[] = {
  { 
    .type = MEMBER_METHOD,
    .name = "createSession",
    .method = &system_media_session_createSession_member_method,
    },
};

// callbacks
static const struct FeatureCallbacks system_media_session_callbacks = {
    system_media_session_onRegister,
    system_media_session_onCreate,
    system_media_session_onRequired,
    system_media_session_onDetached,
    system_media_session_onDestroy,
    system_media_session_onUnregister
};
static const FeatureDescription system_media_session_desc = {
  .version = 1,
  .name = "system.media.session",
  .description = "system.media.session",
  .dynamic = false,
  .native_callbacks = &system_media_session_callbacks,
  .member_count = countof(system_media_session_members),
  .members = system_media_session_members
};
QAPPFEATURE_INIT(system_media_session)
{
    return FeatureRegisterFeature(handle, &system_media_session_desc);
}


/* clang-format on */