/*
 * CopyRight @xiaomi
 * This file is the generated by jidl tools for "PROJECT_ROOT/apps/frameworks/multimedia/media/feature/volume.jidl".
 */
/*
 * Copyright (C) 2025 Xiaomi Corporation. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* clang-format off */
#ifndef JIDL_RUST_GEN_MODULE_SYSTEM_VOLUME_H
#define JIDL_RUST_GEN_MODULE_SYSTEM_VOLUME_H

#include "feature_exports.h"
#include "feature_log.h"

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// FeatureCallbacks to be implemented
void system_volume_onRegister(const char* feature_name);

void system_volume_onCreate(FeatureRuntimeContext ctx, FeatureProtoHandle handle);

void system_volume_onRequired(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);

void system_volume_onDetached(FeatureRuntimeContext ctx, FeatureInstanceHandle handle);

void system_volume_onDestroy(FeatureRuntimeContext ctx, FeatureProtoHandle handle);

void system_volume_onUnregister(const char* feature_name);

// build the predefined
typedef struct system_volume_GetInfo system_volume_GetInfo;
typedef struct system_volume_GetRet system_volume_GetRet;
typedef struct system_volume_SetInfo system_volume_SetInfo;
// Struct define

typedef struct system_volume_GetInfo {
    FtCallbackId success;
    FtCallbackId fail;
    FtCallbackId complete;
} system_volume_GetInfo;

system_volume_GetInfo* system_volumeMallocGetInfo(void);

FeatureType system_volume_GetInfo_struct_get_type (void);
// Struct define

typedef struct system_volume_GetRet {
    FtDouble value;
} system_volume_GetRet;

system_volume_GetRet* system_volumeMallocGetRet(void);

FeatureType system_volume_GetRet_struct_get_type (void);
// callback

// for JIDL callback 'success_cb'
FtBool system_volume_success_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, system_volume_GetRet* ret);
  
// callback

// for JIDL callback 'complete_cb'
FtBool system_volume_complete_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString msg);
  
// Struct define

typedef struct system_volume_SetInfo {
    FtDouble value;
    FtCallbackId success;
    FtCallbackId fail;
    FtCallbackId complete;
} system_volume_SetInfo;

system_volume_SetInfo* system_volumeMallocSetInfo(void);

FeatureType system_volume_SetInfo_struct_get_type (void);
// callback

// for JIDL callback 'fail_cb'
FtBool system_volume_fail_cb_invoke(FeatureInstanceHandle handle, FtCallbackId cid, FtString errorMsg, FtInt code);
  
  
void system_volume_emit_onMediaValueChanged(FeatureInstanceHandle handle , system_volume_GetRet* value);
  
void system_volume_wrap_setMediaValue(FeatureInstanceHandle handle, AppendData adata, system_volume_SetInfo* info);
  
void system_volume_wrap_getMediaValue(FeatureInstanceHandle handle, AppendData adata, system_volume_GetInfo* info);// define the event id
enum {
  system_volume_event_id_begin = 1,






system_volume_onMediaValueChanged_id,
  system_volume_event_id_end,
};

/* clang-format on */
#endif //  JIDL_RUST_GEN_MODULE_SYSTEM_VOLUME_H
